springdoc:
  swagger-ui:
    path: /swagger.html
    enabled: false

server:
  port: 48152

custom:
  activeprofileName: Production

spring:
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password: qwerty
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true